//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.13 at 06:31:31 PM CEST 
//


package entityOutput;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for indicators element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="indicators">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence maxOccurs="unbounded">
 *           &lt;element ref="{}indicator"/>
 *         &lt;/sequence>
 *         &lt;attribute name="ir" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *         &lt;attribute name="te" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "indicator"
})
@XmlRootElement(name = "indicators")
public class Indicators {

    @XmlElement(required = true)
    protected List<Indicator> indicator;
    @XmlAttribute(required = true)
    protected double ir;
    @XmlAttribute(required = true)
    protected double te;

    /**
     * Gets the value of the indicator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indicator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndicator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Indicator }
     * 
     * 
     */
    public List<Indicator> getIndicator() {
        if (indicator == null) {
            indicator = new ArrayList<Indicator>();
        }
        return this.indicator;
    }

    /**
     * Gets the value of the ir property.
     * 
     */
    public double getIr() {
        return ir;
    }

    /**
     * Sets the value of the ir property.
     * 
     */
    public void setIr(double value) {
        this.ir = value;
    }

    /**
     * Gets the value of the te property.
     * 
     */
    public double getTe() {
        return te;
    }

    /**
     * Sets the value of the te property.
     * 
     */
    public void setTe(double value) {
        this.te = value;
    }

}
