//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.14 at 03:35:40 PM CET 
//


package entityOutput;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for indicator element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="indicator">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;attribute name="alpha" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="beta" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="perf" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="period" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *         &lt;attribute name="vol" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "indicator")
public class Indicator {

    @XmlAttribute
    protected String alpha;
    @XmlAttribute
    protected String beta;
    @XmlAttribute
    protected String perf;
    @XmlAttribute
    protected String period;
    @XmlAttribute
    protected String vol;

    /**
     * Gets the value of the alpha property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlpha() {
        return alpha;
    }

    /**
     * Sets the value of the alpha property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlpha(String value) {
        this.alpha = value;
    }

    /**
     * Gets the value of the beta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBeta() {
        return beta;
    }

    /**
     * Sets the value of the beta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBeta(String value) {
        this.beta = value;
    }

    /**
     * Gets the value of the perf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerf() {
        return perf;
    }

    /**
     * Sets the value of the perf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerf(String value) {
        this.perf = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriod(String value) {
        this.period = value;
    }

    /**
     * Gets the value of the vol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVol() {
        return vol;
    }

    /**
     * Sets the value of the vol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVol(String value) {
        this.vol = value;
    }

}
