//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.02 at 11:12:35 PM CEST 
//


package entityOutput;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the entityOutput package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: entityOutput
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Prices }
     * 
     */
    public Prices createPrices() {
        return new Prices();
    }

    /**
     * Create an instance of {@link Stock }
     * 
     */
    public Stock createStock() {
        return new Stock();
    }

    /**
     * Create an instance of {@link Output }
     * 
     */
    public Output createOutput() {
        return new Output();
    }

    /**
     * Create an instance of {@link Obs }
     * 
     */
    public Obs createObs() {
        return new Obs();
    }

    /**
     * Create an instance of {@link Indicators }
     * 
     */
    public Indicators createIndicators() {
        return new Indicators();
    }

    /**
     * Create an instance of {@link Indicator }
     * 
     */
    public Indicator createIndicator() {
        return new Indicator();
    }

}
